[package]
name = "keygen"
version = "0.1.0"
edition = "2021"
authors = ["demfabris demfabris@gmail.com"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
clap = "3.0.14"
directories = "4.0.1"
zeroize = "1.5.2"
